##
## EPITECH PROJECT, 2022
## Epitech-Template
## File description:
## workflow.yml
##

# The goal of this workflow is to merge the remote branch into the Epitech remote, but only if the tests pass.

name: "Push to remote"
on: push

jobs:
  test:
    name: Run tests before pushing to remote
    runs-on: self-hosted

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: 0

      - name: Check if it compiles
        run: |
          make
          make clean
          make fclean
          make re
          ls lib/arcade_centipede.so  lib/arcade_ncurses.so  lib/arcade_nibbler.so  lib/arcade_sdl2.so  lib/arcade_sfml.so ./arcade 2>&1 > /dev/null

      - name: Run tests
        run: "make tests_run"

      - name: Push to Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-OOP-400-LIL-4-1-arcade-quentin.desmettre.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
